//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABRUF
    {
        public Nullable<int> LNR { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> ABDATLVS { get; set; }
        public Nullable<System.DateTime> ABDAT { get; set; }
        public string BEARBLVS { get; set; }
        public string BEARB { get; set; }
        public string SCHICHT { get; set; }
        public string WNR { get; set; }
        public string CPNR { get; set; }
        public Nullable<System.DateTime> ERSTELLT { get; set; }
        public Nullable<System.DateTime> MAT { get; set; }
        public Nullable<System.DateTime> EIN { get; set; }
        public string UB { get; set; }
        public string ABRUFREF { get; set; }
        public Nullable<double> BRUTTO { get; set; }
        public Nullable<double> NETTO { get; set; }
        public string ABLADESTELLE { get; set; }
        public string STAHLLIEFERANT { get; set; }
        public int DFUENR { get; set; }
        public string ACTION { get; set; }
        public string EINHEIT { get; set; }
        public double QUANTITY { get; set; }
    }
}
