//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABRUFSPEED
    {
        public int SATZNR { get; set; }
        public int TESTWERT { get; set; }
        public Nullable<float> DURCHLAUF { get; set; }
        public Nullable<System.DateTime> ZEIT { get; set; }
        public Nullable<System.DateTime> ABLAUF { get; set; }
        public Nullable<int> LOCKS { get; set; }
        public Nullable<decimal> NOFINDS { get; set; }
        public string DUMBOOL { get; set; }
        public string STRING_1 { get; set; }
        public string STRING_2 { get; set; }
        public string STRING_B { get; set; }
    }
}
