//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADR
    {
        public int INCNR { get; set; }
        public string ADRNR { get; set; }
        public string SUCHB { get; set; }
        public string TYP { get; set; }
        public string WERKCODE { get; set; }
        public Nullable<System.DateTime> ERF { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string STRA { get; set; }
        public string PLZ { get; set; }
        public string ORT { get; set; }
        public string AP1 { get; set; }
        public string T1 { get; set; }
        public string AP2 { get; set; }
        public string T2 { get; set; }
        public string FAX { get; set; }
        public string PF { get; set; }
        public string AKEK { get; set; }
        public string BEM { get; set; }
        public Nullable<double> WAGGON { get; set; }
        public Nullable<double> LKW { get; set; }
        public string VERWEIS { get; set; }
        public string KREDKTO { get; set; }
        public string DEBKTO { get; set; }
        public Nullable<int> PFORM { get; set; }
        public string ALLGT { get; set; }
        public string EKAKUB { get; set; }
        public string VERWEIS4913 { get; set; }
        public string VERWEISJOB { get; set; }
        public string VERWEIS4905 { get; set; }
        public string EMAIL { get; set; }
        public string RF1 { get; set; }
        public string RF2 { get; set; }
        public string RSTRA { get; set; }
        public string RPLZ { get; set; }
        public string RORT { get; set; }
        public string RAP { get; set; }
        public string SHORTNAME { get; set; }
        public string ZTEXT { get; set; }
    }
}
