//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART
    {
        public Nullable<int> LNR { get; set; }
        public Nullable<int> BKZ { get; set; }
        public Nullable<double> DI { get; set; }
        public Nullable<double> BR { get; set; }
        public Nullable<double> LAE { get; set; }
        public Nullable<double> BRU { get; set; }
        public Nullable<double> NET { get; set; }
        public string CPNR { get; set; }
        public Nullable<System.DateTime> EDAT { get; set; }
        public Nullable<System.DateTime> ADAT { get; set; }
        public string BEM { get; set; }
        public string ABEM { get; set; }
        public Nullable<int> GT { get; set; }
        public string GTTEXT { get; set; }
        public string ENR { get; set; }
        public string ANR { get; set; }
        public Nullable<double> MENGE { get; set; }
        public string EINHEIT { get; set; }
        public string KDNR { get; set; }
        public string KUNDEF1 { get; set; }
        public string UKNR { get; set; }
        public string UKF1 { get; set; }
        public string EMNR { get; set; }
        public string EMF1 { get; set; }
        public string RAL { get; set; }
        public Nullable<double> WERT { get; set; }
        public Nullable<System.DateTime> UPD { get; set; }
        public Nullable<double> TBRU { get; set; }
        public Nullable<double> TNET { get; set; }
        public Nullable<double> TMENGE { get; set; }
        public Nullable<int> TBKZ { get; set; }
        public Nullable<int> POS { get; set; }
        public string UB { get; set; }
        public string VF { get; set; }
        public string SA { get; set; }
        public Nullable<double> COILD { get; set; }
        public string VVF { get; set; }
        public string KDBEST { get; set; }
        public string VNR { get; set; }
        public string SCHADEN { get; set; }
        public Nullable<int> FRACHT { get; set; }
        public string KDGT { get; set; }
        public string REFNR { get; set; }
        public Nullable<int> PZ { get; set; }
        public string INFOORT { get; set; }
        public string ARTCHECK { get; set; }
        public Nullable<int> DFUENR { get; set; }
        public Nullable<int> TRANSNR { get; set; }
        public Nullable<int> LIEFNR { get; set; }
        public Nullable<int> POSNR { get; set; }
        public string EM { get; set; }
        public string AM { get; set; }
        public Nullable<int> HALLE { get; set; }
        public Nullable<int> REIHE { get; set; }
        public Nullable<int> PREIHE { get; set; }
        public string ARTCHECKA { get; set; }
        public string INDART { get; set; }
        public string SM { get; set; }
        public Nullable<System.DateTime> ABRUFZEIT { get; set; }
        public string WNR { get; set; }
        public Nullable<double> AUGE { get; set; }
        public int STORNO { get; set; }
        public string EM2 { get; set; }
        public string AM2 { get; set; }
        public string SM2 { get; set; }
        public string WNRL { get; set; }
        public string RL { get; set; }
        public string RLM { get; set; }
        public string LSNRL { get; set; }
        public string SWNR { get; set; }
        public string IGNVDA { get; set; }
        public string IGNVDA2 { get; set; }
        public string SPL { get; set; }
        public Nullable<int> LNR_VORUB { get; set; }
        public string PREIHEA { get; set; }
        public double PM { get; set; }
        public string ISPROBLEM { get; set; }
        public string ABRUFREF { get; set; }
        public string AV { get; set; }
        public string TRANSAUFTRAGREF { get; set; }
        public string TQ { get; set; }
        public string UB_SEND { get; set; }
        public Nullable<System.DateTime> REBOOKSPL { get; set; }
        public string ABLADESTELLE { get; set; }
    }
}
