//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA
    {
        public string XNR { get; set; }
        public string TYP { get; set; }
        public Nullable<System.DateTime> XDAT { get; set; }
        public string KUNR { get; set; }
        public string KF1 { get; set; }
        public string KF2 { get; set; }
        public string KF3 { get; set; }
        public string KPLZ { get; set; }
        public string KORT { get; set; }
        public string VENR { get; set; }
        public string VEF1 { get; set; }
        public string VEF2 { get; set; }
        public string VEF3 { get; set; }
        public string VEPLZ { get; set; }
        public string VEORT { get; set; }
        public string BENR { get; set; }
        public string BEF1 { get; set; }
        public string BEF2 { get; set; }
        public string BEF3 { get; set; }
        public string BEPLZ { get; set; }
        public string BEORT { get; set; }
        public string SPED { get; set; }
        public string FZ { get; set; }
        public string LSNR { get; set; }
        public Nullable<System.DateTime> LTAG { get; set; }
        public string XBEM { get; set; }
        public Nullable<double> GBRU { get; set; }
        public Nullable<double> GNET { get; set; }
        public string EKOEMNR { get; set; }
        public string SPNR { get; set; }
        public string SPF1 { get; set; }
        public string SPF2 { get; set; }
        public string SPF3 { get; set; }
        public string SPPLZ { get; set; }
        public string SPORT { get; set; }
        public string FREI { get; set; }
        public string UNFREI { get; set; }
        public string FAHRER { get; set; }
        public string GENNR { get; set; }
        public string FABNR { get; set; }
        public string ANH { get; set; }
        public string ORT { get; set; }
        public string VERSADR { get; set; }
        public string OF1 { get; set; }
        public string OF2 { get; set; }
        public string OF3 { get; set; }
        public string OORT { get; set; }
        public string OPLZ { get; set; }
        public string BEARB { get; set; }
        public string PRINT { get; set; }
        public Nullable<int> DFUENR { get; set; }
        public Nullable<int> TRANSNR { get; set; }
        public Nullable<int> LIEFNR { get; set; }
        public string LIEFERNR { get; set; }
        public string XCHECK { get; set; }
        public Nullable<System.DateTime> MAT { get; set; }
        public string SLB { get; set; }
        public Nullable<System.DateTime> XCHECKDT { get; set; }
    }
}
