//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class GT
    {
        public Nullable<int> NR { get; set; }
        public string TEXT1 { get; set; }
        public string TEXT2 { get; set; }
        public string EINHEIT { get; set; }
        public Nullable<double> WERTTO { get; set; }
        public Nullable<int> MASSE { get; set; }
        public string VERWEIS { get; set; }
        public Nullable<double> BRU { get; set; }
        public Nullable<double> NET { get; set; }
        public Nullable<double> DI { get; set; }
        public Nullable<double> BR { get; set; }
        public Nullable<double> LAE { get; set; }
        public string ORT { get; set; }
        public Nullable<double> MINDEST { get; set; }
        public double PM { get; set; }
        public string GBER { get; set; }
        public string DELBLANK { get; set; }
        public string AKTIV { get; set; }
        public string VERPACKUNGSNR { get; set; }
        public string ABSTBOLZNR { get; set; }
        public int ME_ABSTBOLZ { get; set; }
        public string BESTELLNR { get; set; }
        public string ART { get; set; }
        public string LIEFERANT { get; set; }
    }
}
