//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LvsSZGEntities : DbContext
    {
        public LvsSZGEntities()
            : base("name=LvsSZGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INV> INV { get; set; }
        public virtual DbSet<ABRUF> ABRUF { get; set; }
        public virtual DbSet<ABRUFSPEED> ABRUFSPEED { get; set; }
        public virtual DbSet<ADRGT> ADRGT { get; set; }
        public virtual DbSet<ART> ART { get; set; }
        public virtual DbSet<ARTST> ARTST { get; set; }
        public virtual DbSet<GT> GT { get; set; }
        public virtual DbSet<EA> EAs { get; set; }
        public virtual DbSet<ADR> ADRs { get; set; }
    }
}
