<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Test.aspx.cs" Inherits="Test" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <telerik:RadGrid ID="RadGrid1" runat="server" AllowPaging="True" AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" Culture="de-DE">
        <ExportSettings ExportOnlyData="True" HideStructureColumns="True" IgnorePaging="True" OpenInNewWindow="True">
            <Pdf PageWidth="" PaperSize="A4">
            </Pdf>
            <Excel Format="ExcelML" />
            <Csv EncloseDataWithQuotes="False" />
        </ExportSettings>
        <MasterTableView CommandItemDisplay="Top">
            <CommandItemSettings ShowCancelChangesButton="True" ShowExportToExcelButton="True" ShowExportToPdfButton="True" ShowSaveChangesButton="True" />
        </MasterTableView>
    </telerik:RadGrid>
</asp:Content>

