using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Web.UI;
using System.Web.UI.WebControls;
using Telerik.Web.UI;

public partial class UserList : System.Web.UI.Page
{
    MasterPage myMasterPage;
    clsLogin Login;
    Int32 iColIDIndex = 0;
    private clsUser Benutzer;
    private Int32 iCount = 0;
    private string Default_FileName_ToExport = DateTime.Now.ToString("yyyy_MM_dd_HH_mm") + "_" + "LvsCallUserList";
    private string Default_SiteUserInfotext = "System -> Userverwaltung";
    //public string SiteNav = "[System -> Userverwaltung]";

    ///<summary>UserList / Page_Load</summary>
    ///<remarks></remarks>
    protected void Page_Load(object sender, EventArgs e)
    {
        Login = new clsLogin();
        if (Session["Login"] != null)
        {
            Login = (clsLogin)Session["Login"];
            Login.bInfoText = true;
            Login.InfoText = string.Empty;
            this.Benutzer = new clsUser();
            this.Benutzer = Login.User.Copy();
        }
        else
        {
            Login.InitClass();
            Session["Login"] = Login;
        }

        if ((Login != null) && (Login.LoggedIn))
        {
            myMasterPage = (MasterPage)this.Master;
            Table masterClientInfoTable = (Table)this.Master.FindControl("TableUserInfo");
            if (masterClientInfoTable is Table)
            {
                masterClientInfoTable.Visible = true;
                myMasterPage.SetLableCaption(true, this.Default_SiteUserInfotext);
                myMasterPage.SetLUserInfoHead(this.Login.User.Vorname + " " + this.Login.User.Name);
            }
            if (Page.AppRelativeVirtualPath == Login.AppRelativeVirtualPath)
            {
                //Page.Response.Redirect(Login.NextPagePath);
                Login.AppRelativeVirtualPath = string.Empty;
                Login.NextPagePath = string.Empty;
                Session["Login"] = Login;
            }
        }
    }
    ///<summary>UserList / dgv_NeedDataSource</summary>
    ///<remarks></remarks>
    protected void dgv_NeedDataSource(object sender, Telerik.Web.UI.GridNeedDataSourceEventArgs e)
    {
        InitDGV();
    }
    ///<summary>UserList / InitDGV</summary>
    ///<remarks></remarks>
    protected void InitDGV()
    {
        this.dgv.ExportSettings.FileName = Default_FileName_ToExport;
        this.dgv.ExportSettings.ExportOnlyData = true;
        this.dgv.ExportSettings.Pdf.PageTitle = this.Default_FileName_ToExport;

        List<clsUser> listUserSource = Benutzer.GetUserList();
        this.dgv.MasterTableView.VirtualItemCount = listUserSource.Count;
        this.dgv.DataSource = listUserSource;

        myMasterPage.SetLableCaption(true, this.Default_SiteUserInfotext);
        myMasterPage.SetLUserInfoHead(this.Login.User.Vorname + " " + this.Login.User.Name);
    }
    ///<summary>UserList / dgv_ColumnCreated</summary>
    ///<remarks></remarks>
    protected void dgv_ColumnCreated(object sender, Telerik.Web.UI.GridColumnCreatedEventArgs e)
    {
        GridBoundColumn boundCol;
        string ColName = e.Column.UniqueName;
        switch (ColName)
        {
            case "ID":
                boundCol = e.Column as GridBoundColumn;
                boundCol.Display = true;
                boundCol.ReadOnly = true;
                boundCol.MaxLength = 30;
                break;
            case "Name":
            case "Vorname":
            case "Loginname":
            case "Schicht":
            case "CompanyName":
            case "Rolename":
            case "AddDate":
                boundCol = e.Column as GridBoundColumn;
                boundCol.Display = true;
                boundCol.ReadOnly = true;
                boundCol.MaxLength = 30;
                break;

            case "Passwort":
                boundCol = e.Column as GridBoundColumn;
                boundCol.Display = true;
                boundCol.ReadOnly = true;
                boundCol.Exportable = false;
                break;

            case "InfoText":
            case "RoleID":
            case "CompanyID":
                boundCol = e.Column as GridBoundColumn;
                boundCol.Display = false;
                boundCol.ReadOnly = true;
                break;
            //Spalten ohne Überschrift 

            case "AutoGeneratedDeleteColumn":
                GridButtonColumn btnDel = e.Column as GridButtonColumn;
                if (btnDel is GridButtonColumn)
                {
                    btnDel.ButtonType = GridButtonColumnType.ImageButton;
                    btnDel.ImageUrl = "Images/Delete.gif";
                    btnDel.HeaderTooltip = "Datensatz löschen";
                }
                break;

            case "AutoGeneratedEditColumn":
                GridEditCommandColumn btnEdit = e.Column as GridEditCommandColumn;
                if (btnEdit is GridEditCommandColumn)
                {
                    btnEdit.ButtonType = GridButtonColumnType.ImageButton;
                    btnEdit.EditImageUrl = "Images/Edit.gif";
                    btnEdit.HeaderTooltip = "Datensatz bearbeiten";
                }
                break;

            default:
                e.Column.Display = true;
                e.Column.Exportable = false;
                break;
        }
    }
    ///<summary>UserList / dgv_ItemCreated</summary>
    ///<remarks></remarks>
    protected void dgv_ItemCreated(object sender, Telerik.Web.UI.GridItemEventArgs e)
    {
        clsUser tmp = (clsUser)e.Item.DataItem;

        //string str = e.ToString();
        //switch (e.)
        //{
        //    case "InitInsert":
        //        this.Login.EditUser = null;
        //        Login.AppRelativeVirtualPath = "~/";
        //        Login.NextPagePath = "UserEdit.aspx";
        //        Session["Login"] = Login;
        //        Page.Response.Redirect(Login.NextPagePath);
        //        break;

        //    case "Edit":
        //        Int32 iIndex = 0;
        //        if (Int32.TryParse(e.Item.ItemIndex.ToString(), out iIndex))
        //        {
        //            GridDataItem itm = (GridDataItem)e.Item;
        //            if (itm is GridDataItem)
        //            {
        //                Int32 iID = 0;
        //                if (Int32.TryParse(itm["ID"].ToString(), out iID))
        //                {
        //                    Login.EditUser = new clsUser();
        //                    Login.EditUser.ID = iID;
        //                    Login.EditUser.Fill();

        //                    Login.AppRelativeVirtualPath = "~/";
        //                    Login.NextPagePath = "UserEdit.aspx";
        //                    Session["Login"] = Login;
        //                    Page.Response.Redirect(Login.NextPagePath);
        //                }
        //            }
        //        }
        //        break;

        //    case "Delete":
        //        break;
        //}



        if (tmp != null)
        {
            //(this.dgv.MasterTableView.AutoGeneratedColumns[0] as GridBoundColumn).MaxLength = 5;
            GridEditableItem item = e.Item as GridEditableItem;
            if (item != null && e.Item.IsInEditMode && e.Item.ItemIndex != -1)
            {
        //        List<string> listTmp = new List<string>()
        //        {
        //            "ID"
        //            , "CompanyID"
        //            , "RoleID"
        //            , "Schicht"
        //        };

        //        for (Int32 i = 0; i <= listTmp.Count - 1; i++)
        //        {
        //            string strColName = listTmp[i].ToString();

        //            GridEditManager editMan = item.EditManager;

        //            //IGridColumnEditor editor = editMan.GetColumnEditor("ID");
        //            IGridColumnEditor editor = editMan.GetColumnEditor(strColName);
        //            TextBox box = new TextBox();
        //            RadComboBox cbRole; 
        //            switch (strColName)
        //            { 
        //                case "ID":
        //                    box.Text = tmp.ID.ToString();
        //                    break;

        //                case "CompanyID":
        //                    box.Text = tmp.CompanyName;
        //                    break;

        //                case "RoleID":
        //                    //cbRole = new RadComboBox();
        //                    //InitCheckBoxRole(ref cbRole, tmp.RoleID);
        //                    //box.Text = tmp.RoleID.ToString();

        //                    //foreach (Control ctr in editor.ContainerControl.Controls)
        //                    //{
        //                    //    if (ctr.GetType() == typeof(RadNumericTextBox))
        //                    //    {
        //                    //        editor.ContainerControl.Controls.Remove(ctr);
        //                    //        editor.ContainerControl.Controls.AddAt(0, cbRole);
        //                    //        break;
        //                    //    }
        //                    //    //if (ctr.GetType() == typeof(Literal))
        //                    //    //{
        //                    //    //    tmpLiteral = (Literal)ctr;
        //                    //    //}
        //                    //}
        //                    //editor.ContainerControl.Controls.Add(cbRole);
        //                    //editor.ContainerControl.Controls.Add(tmpLiteral);
        //                    break;

        //                case "Schicht":
        //                    box.Text = tmp.Schicht;
        //                    break;
        //            }
                  
            

        //            ////test
        //            //foreach (Control ctr in editor.ContainerControl.Controls)
        //            //{
        //            //    string strTest = ctr.ID.ToString();
        //            //}


        //            if (editor is IGridColumnEditor)
        //            {
        //                Control control = editor.ContainerControl.Controls[0];
        //                if (control is Control)
        //                {
        //                    if (control.GetType() == typeof(TextBox))
        //                    {
        //                        TextBox tbox = (TextBox)control;
        //                        tbox.Enabled = false;
        //                    }
        //                    if (control.GetType() == typeof(RadTextBox))
        //                    {
        //                        RadTextBox tbox = (RadTextBox)control;
        //                        tbox.Enabled = false;
        //                    }
        //                    if (control.GetType() == typeof(RadNumericTextBox))
        //                    {
        //                        RadNumericTextBox tbox = (RadNumericTextBox)control;
        //                        tbox.Enabled = false;
        //                    }
        //                }
        //            }
        //        }

            }
        }
    }
    ///<summary>UserList / dgv_ItemCommand</summary>
    ///<remarks>Editieren, löschen, hinzufügen >>> Handled für das Grid</remarks>
    protected void dgv_ItemCommand(object sender, Telerik.Web.UI.GridCommandEventArgs e)
    {        
        for (Int32 i = 0; i <= this.dgv.Columns.Count - 1; i++)
        {
            if (this.dgv.Columns[i].UniqueName.Equals("ID"))
            {
                iColIDIndex = i;
                i = this.dgv.Columns.Count;
            }
        }
        string str = e.ToString();
        Int32 iIndex = 0;
        switch (e.CommandName)
        {
            case "InitInsert":
                this.Login.EditUser = null;
                Login.AppRelativeVirtualPath = "~/";
                Login.NextPagePath = "UserEdit.aspx";
                Session["Login"] = Login;
                Page.Response.Redirect(Login.NextPagePath);
                break;

            case "Edit":
                //iIndex = iColIDIndex;
                if (Int32.TryParse(e.Item.ItemIndex.ToString(), out iIndex))
                {
                    //aktuell ist der Columnindex für ID = 4 
                    //Dieser müsste noch dynmaisch ermittelt werden
                    //iColIDIndex = 4;
                    
                    GridDataItem itm = (GridDataItem)this.dgv.Items[iIndex];
                    //string strl = itm["ID"].Text;
                    string strUserTableID = itm["ID"].Text; 
                    Int32 iID = 0;
                    if (Int32.TryParse(strUserTableID, out iID))
                    {
                        Login.EditUser = new clsUser();
                        Login.EditUser.ID = iID;
                        Login.EditUser.Fill();

                        Login.AppRelativeVirtualPath = "~/";
                        Login.NextPagePath = "UserEdit.aspx";
                        Session["Login"] = Login;
                        Page.Response.Redirect(Login.NextPagePath);
                    }
   
                }
                break;

            case "Delete":
                if (Int32.TryParse(e.Item.ItemIndex.ToString(), out iIndex))
                {
                    //aktuell ist der Columnindex für ID = 4 
                    //Dieser müsste noch dynmaisch ermittelt werden
                    GridDataItem itm = (GridDataItem)this.dgv.Items[iIndex];
                    string strl = itm["ID"].Text;
                    //string str2 = itm["ArtikelID"].Text;

                    string strUsrTableID = itm["ID"].Text;
                    Int32 iID = 0;
                    if (Int32.TryParse(strUsrTableID, out iID))
                    {
                        Login.EditUser = new clsUser();
                        Login.EditUser.ID = iID;
                        Login.EditUser.Delete();

                        Login.AppRelativeVirtualPath = "~/";
                        Login.NextPagePath = "UserList.aspx";
                        Session["Login"] = Login;
                        Page.Response.Redirect(Login.NextPagePath);
                    }
                }
                break;
        }

    }
 
    ///<summary>UserList / dgv_GridExporting</summary>
    ///<remarks></remarks>
    protected void dgv_GridExporting(object sender, GridExportingArgs e)
    {
        switch (e.ExportType)
        {
            case ExportType.Excel:
                //do something with the e.ExportOutput value  
                this.dgv.MasterTableView.ExportToExcel();
                break;
            case ExportType.ExcelML:
                //do something with the e.ExportOutput value     
                break;
            case ExportType.Word:
                //do something with the e.ExportOutput value       
                break;
            case ExportType.Csv:
                //do something with the e.ExportOutput value    
                break;
            case ExportType.Pdf:
                //you can't change the output here - use the PdfExporting event instead   
                foreach (GridDataItem item in dgv.Items)
                    item.Style["background-color"] = "#888888";
                this.dgv.MasterTableView.ExportToPdf();
                break;
        }
    }
  
 
}