<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="UserList.aspx.cs" Inherits="UserList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        #DGV
        {
            width: 1447px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div id="DGV"> 
        <telerik:RadGrid ID="dgv" runat="server" 
            OnNeedDataSource="dgv_NeedDataSource" 
            AllowPaging="True" 
            AllowSorting="True" 
            AutoGenerateDeleteColumn="True"
            AutoGenerateEditColumn="True" 
            Culture="de-DE" 
            OnColumnCreated="dgv_ColumnCreated"  
            OnItemCommand="dgv_ItemCommand" 
            OnItemCreated="dgv_ItemCreated" 

            Skin="Office2010Blue" 
            ShowDesignTimeSmartTagMessage="False" 
            OnGridExporting="dgv_GridExporting" 
            ShowFooter="True" 
            ShowStatusBar="True" PageSize="25">
            <ExportSettings HideStructureColumns="True" IgnorePaging="True" ExportOnlyData="True" FileName="" OpenInNewWindow="True">
                <Pdf PageHeight="210mm" PageWidth="297mm" PaperSize="A4">
                </Pdf>
            </ExportSettings>
            <ClientSettings AllowAutoScrollOnDragDrop="False" AllowColumnsReorder="True">
                <Selecting AllowRowSelect="True" />
                <Scrolling EnableVirtualScrollPaging="True" ScrollHeight="600px" />
            </ClientSettings>
            <MasterTableView CommandItemDisplay="Top" EditMode="PopUp">
                <CommandItemSettings ShowExportToExcelButton="True" AddNewRecordText="Neuen User anlegen" CancelChangesText="Bearbeitung abbrechen" ExportToCsvText="Export zu CSV" ExportToExcelText="Export zu Excel" ExportToPdfText="Export zu PDF" ExportToWordText="Export zu Word" RefreshText="Liste aktualisieren" SaveChangesText="Userdaten bearbeiten" />
                <RowIndicatorColumn Visible="False">
                </RowIndicatorColumn>
                <ExpandCollapseColumn Created="True">
                </ExpandCollapseColumn>
                <EditFormSettings>
                    <EditColumn ButtonType="ImageButton" HeaderButtonType="PushButton">
                    </EditColumn>
                </EditFormSettings>
                <PagerStyle AlwaysVisible="True" />
            </MasterTableView>
            <EditItemStyle BackColor="White" />
            <StatusBarSettings LoadingText="Daten werden geladen....." ReadyText="Daten geladen !!!" />
            <HeaderContextMenu AppendDataBoundItems="True">
            </HeaderContextMenu>
        </telerik:RadGrid>
    </div>
</asp:Content>

